const RoutesAdminiApp = [
/**** Start - Admin App ****/
  {
    path: '/admin-app/',
    redirect: '/admin-app/dashboard',
  },
  {
    path: '/admin-app/dashboard',
    name: 'Dashboard',
    icon: 'Dashboard',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/dashboard',
  },
  {
    path: '/admin-app/profile',
    name: 'Profile',
    hideInMenu: true,
    layout: 'mix',
    component: './admin-app/current-user/profile',
  },
  {
    path: '/admin-app/categories',
    name: 'Categories Management',
    icon: 'AppstoreAddOutlined',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/categories-management/list-categories',
  },
  {
    path: '/admin-app/categories/new',
    hideInMenu: true,
    name: 'Create Category',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/categories-management/create-category',
  },
  {
    path: '/admin-app/categories/edit/:id',
    hideInMenu: true,
    name: 'Edit Category',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/categories-management/update-category',
  },
  {
    path: '/admin-app/tutors',
    name: 'Tutors Management',
    icon: 'UsergroupAddOutlined',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/tutors-management/list-tutors',
  },
  {
    path: '/admin-app/tutors/new',
    hideInMenu: true,
    name: 'Create Tutor',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/tutors-management/create-tutor',
  },
  {
    path: '/admin-app/tutors/edit/:id',
    hideInMenu: true,
    name: 'Edit Tutor',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/tutors-management/update-tutor',
  },
  {
    path: '/admin-app/users',
    name: 'Users Management',
    icon: 'TeamOutlined',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/users-management/list-users',
  },
  {
    path: '/admin-app/users/new',
    hideInMenu: true,
    name: 'Create User',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/users-management/create-user',
  },
  {
    path: '/admin-app/users/edit/:id',
    hideInMenu: true,
    name: 'Edit User',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/users-management/update-user',
  },
  {
    path: '/admin-app/fee-vouchers',
    name: 'Fee Vouchers Management',
    icon: 'FileProtectOutlined',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/fee-vouchers-management/list-fee-vouchers',
  },
  {
    path: '/admin-app/fee-vouchers/edit/:id',
    hideInMenu: true,
    name: 'Edit Fee Voucher',
    access: 'isAdministrator',
    layout: 'mix',
    component: './admin-app/fee-vouchers-management/update-fee-voucher',
  },
  /**** Start - Admin App ****/
];
export default RoutesAdminiApp;